#' Define tools available to the xen.assist agent
#' @importFrom ellmer tool
#' @export
get_xen_tools <- function() {
  if (!requireNamespace("ellmer", quietly = TRUE)) {
    stop("Package 'ellmer' is required for tool definition.")
  }

  # --- Wrapper functions to ensure JSON-serializable output ---
  
  tool_et_scale_generate <- function(period, divisions, root_freq) {
    res <- et_scale_generate(period, divisions, root_freq)
    return(as.data.frame(res))
  }

  tool_cps_scale_table <- function(harmonics, choose, root_divisor) {
    res <- cps_scale_table(harmonics, choose, root_divisor)
    return(as.data.frame(res))
  }

  tool_ps_scale_table <- function(ps_def, root_divisor) {
    res <- ps_scale_table(ps_def, root_divisor)
    return(as.data.frame(res))
  }

  tool_interval_table <- function(scale_table) {
    dt <- data.table::as.data.table(scale_table)
    res <- interval_table(dt)
    return(as.data.frame(res))
  }

  tool_keyboard_map <- function(scale_table, middle_c_octave = 4) {
    dt <- data.table::as.data.table(scale_table)
    res <- keyboard_map(dt, middle_c_octave = middle_c_octave)
    return(as.data.frame(res))
  }

  tool_note_synth <- function(freq, signal, duration_sec, velocity, sample_rate_hz = 48000, bit_width = 24) {
    wave <- note_synth(freq, signal, duration_sec, velocity, sample_rate_hz, bit_width)
    fname <- tempfile(fileext = ".wav")
    tuneR::writeWave(wave, fname)
    return(paste0("Successfully synthesized note at ", freq, "Hz. Saved to: ", fname))
  }

  tool_chord_synth <- function(chord, signal, duration_sec, velocity, sample_rate_hz = 48000, bit_width = 24) {
    wave <- chord_synth(chord, signal, duration_sec, velocity, sample_rate_hz, bit_width)
    fname <- tempfile(fileext = ".wav")
    tuneR::writeWave(wave, fname)
    return(paste0("Successfully synthesized chord. Saved to: ", fname))
  }

  list(
    ellmer::tool(
      fun = tool_et_scale_generate,
      description = "Create an equal-tempered scale (EDO). Useful for generating standard or xentonal EDOs.",
      arguments = list(
        period = ellmer::type_number(description = "The period of the scale. Use 2.0 for octave, 3.0 for tritave (Bohlen-Pierce), etc."),
        divisions = ellmer::type_integer(description = "Number of equal divisions in the period (e.g., 12, 19, 31)."),
        root_freq = ellmer::type_number(description = "The root frequency of the scale in Hz.")
      )
    ),
    ellmer::tool(
      fun = tool_cps_scale_table,
      description = "Create a Combination Product Set (CPS) scale table. These are scales derived from sets of harmonic numbers.",
      arguments = list(
        harmonics = ellmer::type_array(ellmer::type_number(), description = "A numeric vector of harmonics to use (e.g., c(1, 3, 5, 7))."),
        choose = ellmer::type_integer(description = "The number of harmonics to choose for each combination (usually half the length of harmonics + 1)."),
        root_divisor = ellmer::type_number(description = "The divisor used to normalize the scale (sets the tonic frequency).")
      )
    ),
    ellmer::tool(
      fun = tool_ps_scale_table,
      description = "Create a product set scale table from explicit products (e.g., '1x3', '1x5').",
      arguments = list(
        ps_def = ellmer::type_array(ellmer::type_string(), description = "A character vector of products (e.g., c('1x3', '1x5'))."),
        root_divisor = ellmer::type_number(description = "The divisor used to normalize the scale.")
      )
    ),
    ellmer::tool(
      fun = tool_interval_table,
      description = "Generate an interval table from an existing scale table. Useful for analyzing harmonic relationships.",
      arguments = list(
        scale_table = ellmer::type_string(description = "A scale table (as a JSON object/list) generated by et_scale_generate, cps_scale_table, or ps_scale_table.")
      )
    ),
    ellmer::tool(
      fun = tool_keyboard_map,
      description = "Create a MIDI keyboard mapping for a scale. Helps map xentonal notes to physical keys.",
      arguments = list(
        scale_table = ellmer::type_string(description = "A scale table (as a JSON object/list)."),
        middle_c_octave = ellmer::type_integer(description = "The octave number for middle C (default 4).")
      )
    ),
    ellmer::tool(
      fun = tool_note_synth,
      description = "Synthesize a single audio note and save it to a temporary WAV file.",
      arguments = list(
        freq = ellmer::type_number(description = "Frequency in Hz."),
        signal = ellmer::type_string(description = "Waveform type: 'sine', 'tria', 'square', or 'saw'."),
        duration_sec = ellmer::type_number(description = "Duration of the note in seconds."),
        velocity = ellmer::type_integer(description = "MIDI velocity (0-127)."),
        sample_rate_hz = ellmer::type_integer(description = "Sample rate in Hz. Defaults to 48000."),
        bit_width = ellmer::type_integer(description = "Bit width (8, 16, 24, 32, 64). Defaults to 24.")
      )
    ),
    ellmer::tool(
      fun = tool_chord_synth,
      description = "Synthesize a chord and save it to a temporary WAV file.",
      arguments = list(
        chord = ellmer::type_array(ellmer::type_number(), description = "A numeric vector of frequencies for the chord."),
        signal = ellmer::type_string(description = "Waveform type: 'sine', 'tria', 'square', or 'saw'."),
        duration_sec = ellmer::type_number(description = "Duration in seconds."),
        velocity = ellmer::type_integer(description = "MIDI velocity (0-127)."),
        sample_rate_hz = ellmer::type_integer(description = "Sample rate in Hz. Defaults to 48000."),
        bit_width = ellmer::type_integer(description = "Bit width (8, 16, 24, 32, 64). Defaults to 24.")
      )
    )
  )
}